 export const courses = [
  {
    id: 1,
    title: "React Basics",
    instructor: "John Doe",
    duration: "6 Weeks",
    level: "Beginner",
    category: "Frontend",
    price: 1999,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Advanced React",
    instructor: "Sarah Lee",
    duration: "8 Weeks",
    level: "Advanced",
    category: "Frontend",
    price: 3499,
    rating: 4.8,
  },
  {
    id: 3,
    title: "JavaScript Mastery",
    instructor: "David Miller",
    duration: "10 Weeks",
    level: "Intermediate",
    category: "JavaScript",
    price: 2999,
    rating: 4.7,
  },
  {
    id: 4,
    title: "Node.js Fundamentals",
    instructor: "Emma Watson",
    duration: "5 Weeks",
    level: "Beginner",
    category: "Backend",
    price: 2499,
    rating: 4.4,
  },
  {
    id: 5,
    title: "Express.js API Development",
    instructor: "Chris Evans",
    duration: "7 Weeks",
    level: "Intermediate",
    category: "Backend",
    price: 2799,
    rating: 4.6,
  },
  {
    id: 6,
    title: "MongoDB Essentials",
    instructor: "Sophia Green",
    duration: "4 Weeks",
    level: "Beginner",
    category: "Database",
    price: 1899,
    rating: 4.3,
  },
  {
    id: 7,
    title: "Full Stack MERN",
    instructor: "Michael Scott",
    duration: "12 Weeks",
    level: "Advanced",
    category: "Full Stack",
    price: 4999,
    rating: 4.9,
  },
  {
    id: 8,
    title: "HTML & CSS Bootcamp",
    instructor: "Robert Brown",
    duration: "3 Weeks",
    level: "Beginner",
    category: "Frontend",
    price: 1499,
    rating: 4.2,
  },
  {
    id: 9,
    title: "Tailwind CSS Masterclass",
    instructor: "Lisa Ray",
    duration: "4 Weeks",
    level: "Intermediate",
    category: "Frontend",
    price: 2299,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Redux Complete Guide",
    instructor: "Daniel White",
    duration: "6 Weeks",
    level: "Intermediate",
    category: "Frontend",
    price: 2699,
    rating: 4.6,
  },
  {
    id: 11,
    title: "TypeScript for Beginners",
    instructor: "Kevin Hart",
    duration: "5 Weeks",
    level: "Beginner",
    category: "Programming",
    price: 2199,
    rating: 4.4,
  },
  {
    id: 12,
    title: "Next.js Crash Course",
    instructor: "Natalie Portman",
    duration: "6 Weeks",
    level: "Intermediate",
    category: "Frontend",
    price: 3299,
    rating: 4.7,
  },
  {
    id: 13,
    title: "Firebase Authentication",
    instructor: "Tom Hardy",
    duration: "3 Weeks",
    level: "Beginner",
    category: "Backend",
    price: 1799,
    rating: 4.3,
  },
  {
    id: 14,
    title: "Python for Developers",
    instructor: "Henry Clark",
    duration: "8 Weeks",
    level: "Beginner",
    category: "Programming",
    price: 2599,
    rating: 4.5,
  },
  {
    id: 15,
    title: "Data Structures in JavaScript",
    instructor: "Olivia Taylor",
    duration: "7 Weeks",
    level: "Intermediate",
    category: "DSA",
    price: 2899,
    rating: 4.8,
  },
  {
    id: 16,
    title: "Algorithms Masterclass",
    instructor: "James Wilson",
    duration: "9 Weeks",
    level: "Advanced",
    category: "DSA",
    price: 3999,
    rating: 4.9,
  },
  {
    id: 17,
    title: "Git & GitHub",
    instructor: "Emily Davis",
    duration: "2 Weeks",
    level: "Beginner",
    category: "Tools",
    price: 999,
    rating: 4.2,
  },
  {
    id: 18,
    title: "Docker Essentials",
    instructor: "Ryan Cooper",
    duration: "5 Weeks",
    level: "Intermediate",
    category: "DevOps",
    price: 3199,
    rating: 4.6,
  },
  {
    id: 19,
    title: "AWS Cloud Basics",
    instructor: "Sophia Turner",
    duration: "6 Weeks",
    level: "Beginner",
    category: "Cloud",
    price: 3599,
    rating: 4.5,
  },
  {
    id: 20,
    title: "Kubernetes Fundamentals",
    instructor: "Andrew Parker",
    duration: "8 Weeks",
    level: "Advanced",
    category: "DevOps",
    price: 4599,
    rating: 4.7,
  },
  {
    id: 21,
    title: "Machine Learning Intro",
    instructor: "Ethan Brooks",
    duration: "10 Weeks",
    level: "Intermediate",
    category: "AI",
    price: 4999,
    rating: 4.8,
  },
  {
    id: 22,
    title: "Deep Learning with Python",
    instructor: "Ava Martinez",
    duration: "12 Weeks",
    level: "Advanced",
    category: "AI",
    price: 5999,
    rating: 4.9,
  },
  {
    id: 23,
    title: "SQL Database Mastery",
    instructor: "Noah Anderson",
    duration: "5 Weeks",
    level: "Intermediate",
    category: "Database",
    price: 2499,
    rating: 4.4,
  },
  {
    id: 24,
    title: "PostgreSQL Complete Guide",
    instructor: "Mia Robinson",
    duration: "6 Weeks",
    level: "Intermediate",
    category: "Database",
    price: 2799,
    rating: 4.5,
  },
  {
    id: 25,
    title: "C Programming Basics",
    instructor: "William Scott",
    duration: "4 Weeks",
    level: "Beginner",
    category: "Programming",
    price: 1599,
    rating: 4.1,
  },
  {
    id: 26,
    title: "Java Programming",
    instructor: "Charlotte Lewis",
    duration: "8 Weeks",
    level: "Intermediate",
    category: "Programming",
    price: 2999,
    rating: 4.6,
  },
  {
    id: 27,
    title: "Spring Boot Development",
    instructor: "Benjamin Hall",
    duration: "9 Weeks",
    level: "Advanced",
    category: "Backend",
    price: 4499,
    rating: 4.8,
  },
  {
    id: 28,
    title: "PHP & Laravel",
    instructor: "Amelia Young",
    duration: "7 Weeks",
    level: "Intermediate",
    category: "Backend",
    price: 2799,
    rating: 4.4,
  },
  {
    id: 29,
    title: "Vue.js Essentials",
    instructor: "Jacob King",
    duration: "5 Weeks",
    level: "Beginner",
    category: "Frontend",
    price: 2199,
    rating: 4.3,
  },
  {
    id: 30,
    title: "Angular Complete Course",
    instructor: "Ella Wright",
    duration: "9 Weeks",
    level: "Advanced",
    category: "Frontend",
    price: 3999,
    rating: 4.7,
  },
  {
    id: 31,
    title: "Cyber Security Basics",
    instructor: "Lucas Hill",
    duration: "6 Weeks",
    level: "Beginner",
    category: "Security",
    price: 3299,
    rating: 4.5,
  },
  {
    id: 32,
    title: "Ethical Hacking",
    instructor: "Harper Adams",
    duration: "10 Weeks",
    level: "Advanced",
    category: "Security",
    price: 5499,
    rating: 4.8,
  },
  {
    id: 33,
    title: "UI/UX Design Fundamentals",
    instructor: "Alexander Baker",
    duration: "4 Weeks",
    level: "Beginner",
    category: "Design",
    price: 1999,
    rating: 4.2,
  },
  {
    id: 34,
    title: "Figma Masterclass",
    instructor: "Grace Nelson",
    duration: "3 Weeks",
    level: "Intermediate",
    category: "Design",
    price: 2299,
    rating: 4.4,
  },
  {
    id: 35,
    title: "React Native App Development",
    instructor: "Matthew Carter",
    duration: "8 Weeks",
    level: "Advanced",
    category: "Mobile",
    price: 4599,
    rating: 4.7,
  },
  {
    id: 36,
    title: "Flutter for Beginners",
    instructor: "Lily Mitchell",
    duration: "7 Weeks",
    level: "Beginner",
    category: "Mobile",
    price: 3499,
    rating: 4.5,
  },
  {
    id: 37,
    title: "Data Analysis with Excel",
    instructor: "David Perez",
    duration: "4 Weeks",
    level: "Beginner",
    category: "Data Analysis",
    price: 1799,
    rating: 4.1,
  },
  {
    id: 38,
    title: "Power BI Dashboarding",
    instructor: "Victoria Roberts",
    duration: "5 Weeks",
    level: "Intermediate",
    category: "Data Analysis",
    price: 2999,
    rating: 4.6,
  },
  {
    id: 39,
    title: "Blockchain Fundamentals",
    instructor: "Joseph Turner",
    duration: "6 Weeks",
    level: "Intermediate",
    category: "Blockchain",
    price: 3999,
    rating: 4.5,
  },
  {
    id: 40,
    title: "Solidity Smart Contracts",
    instructor: "Zoe Phillips",
    duration: "9 Weeks",
    level: "Advanced",
    category: "Blockchain",
    price: 5499,
    rating: 4.8,
  },
  {
    id: 41,
    title: "Operating System Concepts",
    instructor: "Nathan Campbell",
    duration: "5 Weeks",
    level: "Intermediate",
    category: "Computer Science",
    price: 2599,
    rating: 4.3,
  },
  {
    id: 42,
    title: "Computer Networks",
    instructor: "Hannah Parker",
    duration: "6 Weeks",
    level: "Intermediate",
    category: "Computer Science",
    price: 2799,
    rating: 4.4,
  },
  {
    id: 43,
    title: "System Design Basics",
    instructor: "Leo Collins",
    duration: "8 Weeks",
    level: "Advanced",
    category: "Architecture",
    price: 4999,
    rating: 4.9,
  },
  {
    id: 44,
    title: "Linux Command Line",
    instructor: "Scarlett Edwards",
    duration: "3 Weeks",
    level: "Beginner",
    category: "Tools",
    price: 1499,
    rating: 4.2,
  },
  {
    id: 45,
    title: "Jenkins CI/CD Pipeline",
    instructor: "Gabriel Flores",
    duration: "5 Weeks",
    level: "Advanced",
    category: "DevOps",
    price: 3699,
    rating: 4.6,
  },
  {
    id: 46,
    title: "GraphQL API Development",
    instructor: "Chloe Morris",
    duration: "6 Weeks",
    level: "Intermediate",
    category: "Backend",
    price: 3399,
    rating: 4.5,
  },
  {
    id: 47,
    title: "SASS & Responsive Design",
    instructor: "Jack Murphy",
    duration: "4 Weeks",
    level: "Beginner",
    category: "Frontend",
    price: 1899,
    rating: 4.3,
  },
  {
    id: 48,
    title: "Web Performance Optimization",
    instructor: "Aria Cook",
    duration: "5 Weeks",
    level: "Advanced",
    category: "Frontend",
    price: 3199,
    rating: 4.7,
  },
  {
    id: 49,
    title: "Competitive Programming",
    instructor: "Samuel Reed",
    duration: "10 Weeks",
    level: "Advanced",
    category: "DSA",
    price: 4299,
    rating: 4.8,
  },
  {
    id: 50,
    title: "Software Testing & QA",
    instructor: "Penelope Ward",
    duration: "6 Weeks",
    level: "Intermediate",
    category: "Testing",
    price: 2499,
    rating: 4.4,
  },
];